services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: carsell
    ports:
      - "5440:5432"
    volumes:
      - carpgdata:/var/lib/postgresql/data
volumes:
  carpgdata: