server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/carsell
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com:
      carsell:
        platform: DEBUG
      fasterxml:
        jackson: DEBUG
    org:
      springframework:
        http:
          converter: DEBUG
        web:
          servlet:
            mvc:
              method:
                annotation: DEBUG

jwt:
  secret: "YourBase64EncodedSecretKeyThatIsAtLeast512BitsLongForHS512Algorithm"
  expirationMs: 86400000